version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chattr-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: chattr
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chattr-network

  redis:
    image: redis:7-alpine
    container_name: chattr-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chattr-network

  app:
    build: .
    container_name: chattr
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - chattr-network

volumes:
  mysql_data:

networks:
  chattr-network:
    driver: bridge