version: '3.8'

services:
  app:
    image: kimje22/chattr:latest
    container_name: chattr
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - chattr-network

  mysql:
    image: mysql:8.0
    container_name: chattr-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: chattr
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chattr-network

  redis:
    image: redis:7-alpine
    container_name: chattr-redis
    restart: always
    networks:
      - chattr-network

volumes:
  mysql_data:

networks:
  chattr-network:
    driver: bridge