version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chattr-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 693256
      MYSQL_DATABASE: chattr
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chattr-network

  redis:
    image: redis:7-alpine
    container_name: chattr-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chattr-network

  app:
    image: ${DOCKER_USERNAME}/chattr:latest
    container_name: chattr
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/chattr
      - DB_USERNAME=root
      - DB_PASS=693256
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HIBERNATE_DDL_AUTO=update
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    networks:
      - chattr-network

volumes:
  mysql_data:

networks:
  chattr-network:
    driver: bridge